rootProject.name = "bisq-x"
include(
    "apps:cli",
    "apps:desktop",
    "apps:daemon",
    "clients:java",
    "core:oas",
    "core:node",
    "core:domain",
    "core:domain:trading",
    "core:network",
    "core:network:http",
    "core:network:p2p",
    "core:logging",
    "core:api",
    "core",
    "demos:marketmaker",
    "demos:satstacker",
)
