openapi: 3.0.1
info:
  title: bisq-openapi
  version: 2.1.0
servers:
- url: /
paths:
  /identities:
    post:
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_request'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: create 200 response
      tags:
      - User
      x-content-type: application/json
      x-accepts:
      - application/json
  /info:
    get:
      operationId: getInfo
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info'
          description: getInfo 200 response
      tags:
      - Info
      x-accepts:
      - application/json
  /logging/categories:
    get:
      operationId: getCategories
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/LoggingCategory'
                type: array
          description: getCategories 200 response
      tags:
      - Logging
      x-accepts:
      - application/json
    put:
      operationId: updateCategory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateCategory_request'
        required: true
      responses:
        "200":
          description: updateCategory 200 response
      tags:
      - Logging
      x-content-type: application/json
      x-accepts:
      - application/json
  /logging/categories/{name}:
    get:
      operationId: getCategory
      parameters:
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoggingCategory'
          description: getCategory 200 response
      tags:
      - Logging
      x-accepts:
      - application/json
  /trade/offers:
    get:
      operationId: listAll
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Offer'
                type: array
          description: listAll 200 response
      tags:
      - Offer
      x-accepts:
      - application/json
    post:
      operationId: add
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add_request'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: add 200 response
      tags:
      - Offer
      x-content-type: application/json
      x-accepts:
      - application/json
  /trade/offers/{id}:
    delete:
      operationId: delete
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'
          description: delete 200 response
      tags:
      - Offer
      x-accepts:
      - application/json
    get:
      operationId: show
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'
          description: show 200 response
      tags:
      - Offer
      x-accepts:
      - application/json
components:
  schemas:
    Identity:
      properties:
        nym:
          minLength: 1
          type: string
      required:
      - nym
      type: object
    Info:
      example:
        version: version
      properties:
        version:
          minLength: 1
          type: string
      required:
      - version
      type: object
    LoggingCategory:
      example:
        level: level
        name: name
      properties:
        name:
          minLength: 1
          type: string
        level:
          minLength: 1
          type: string
      required:
      - level
      - name
      type: object
    Offer:
      example:
        details: details
        id: id
      properties:
        id:
          type: string
        details:
          minLength: 1
          type: string
      required:
      - details
      - id
      type: object
    create_request:
      properties:
        identity:
          $ref: '#/components/schemas/Identity'
      type: object
    updateCategory_request:
      properties:
        loggingCategory:
          $ref: '#/components/schemas/LoggingCategory'
      type: object
    add_request:
      properties:
        offer:
          $ref: '#/components/schemas/Offer'
      type: object

