/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package bisq.client.kotlin.models

import bisq.client.kotlin.models.LoggingCategory

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param loggingCategory 
 */


data class UpdateLoggingCategoryRequest (

    @Json(name = "loggingCategory")
    val loggingCategory: LoggingCategory? = null

)

