/*
 * bisq-openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bisq.client.java.models;

import java.util.Objects;
import bisq.client.java.models.LoggingCategory;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import bisq.client.java.JSON;

/**
 * UpdateLoggingCategoryRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.6.0")
public class UpdateLoggingCategoryRequest {
  public static final String SERIALIZED_NAME_LOGGING_CATEGORY = "loggingCategory";
  @SerializedName(SERIALIZED_NAME_LOGGING_CATEGORY)
  private LoggingCategory loggingCategory;

  public UpdateLoggingCategoryRequest() {
  }

  public UpdateLoggingCategoryRequest loggingCategory(LoggingCategory loggingCategory) {
    this.loggingCategory = loggingCategory;
    return this;
  }

   /**
   * Get loggingCategory
   * @return loggingCategory
  **/
  @javax.annotation.Nullable
  public LoggingCategory getLoggingCategory() {
    return loggingCategory;
  }

  public void setLoggingCategory(LoggingCategory loggingCategory) {
    this.loggingCategory = loggingCategory;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateLoggingCategoryRequest updateLoggingCategoryRequest = (UpdateLoggingCategoryRequest) o;
    return Objects.equals(this.loggingCategory, updateLoggingCategoryRequest.loggingCategory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loggingCategory);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateLoggingCategoryRequest {\n");
    sb.append("    loggingCategory: ").append(toIndentedString(loggingCategory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("loggingCategory");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to UpdateLoggingCategoryRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateLoggingCategoryRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateLoggingCategoryRequest is not found in the empty JSON string", UpdateLoggingCategoryRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateLoggingCategoryRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateLoggingCategoryRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `loggingCategory`
      if (jsonObj.get("loggingCategory") != null && !jsonObj.get("loggingCategory").isJsonNull()) {
        LoggingCategory.validateJsonElement(jsonObj.get("loggingCategory"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateLoggingCategoryRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateLoggingCategoryRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateLoggingCategoryRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateLoggingCategoryRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateLoggingCategoryRequest>() {
           @Override
           public void write(JsonWriter out, UpdateLoggingCategoryRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateLoggingCategoryRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UpdateLoggingCategoryRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UpdateLoggingCategoryRequest
  * @throws IOException if the JSON string is invalid with respect to UpdateLoggingCategoryRequest
  */
  public static UpdateLoggingCategoryRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateLoggingCategoryRequest.class);
  }

 /**
  * Convert an instance of UpdateLoggingCategoryRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

