/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package bisq.client.kotlin.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bisq.client.kotlin.models.AddOfferRequest
import bisq.client.kotlin.models.Offer

class AddOfferRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AddOfferRequest
        //val modelInstance = AddOfferRequest()

        // to test the property `offer`
        should("test offer") {
            // uncomment below to test the property
            //modelInstance.offer shouldBe ("TODO")
        }

    }
}
