/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package bisq.client.kotlin.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bisq.client.kotlin.models.Identity

class IdentityTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Identity
        //val modelInstance = Identity()

        // to test the property `nym`
        should("test nym") {
            // uncomment below to test the property
            //modelInstance.nym shouldBe ("TODO")
        }

    }
}
