/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package bisq.client.kotlin.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bisq.client.kotlin.models.UpdateLoggingCategoryRequest
import bisq.client.kotlin.models.LoggingCategory

class UpdateLoggingCategoryRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateLoggingCategoryRequest
        //val modelInstance = UpdateLoggingCategoryRequest()

        // to test the property `loggingCategory`
        should("test loggingCategory") {
            // uncomment below to test the property
            //modelInstance.loggingCategory shouldBe ("TODO")
        }

    }
}
