/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.InfoApi
import org.openapitools.client.models.Info

class InfoApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InfoApi
        //val apiInstance = InfoApi()

        // to test getInfo
        should("test getInfo") {
            // uncomment below to test getInfo
            //val result : Info = apiInstance.getInfo()
            //result shouldBe ("TODO")
        }

    }
}
