/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.UserApi
import org.openapitools.client.models.CreateRequest

class UserApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserApi
        //val apiInstance = UserApi()

        // to test create
        should("test create") {
            // uncomment below to test create
            //val createRequest : CreateRequest =  // CreateRequest | 
            //val result : kotlin.Any = apiInstance.create(createRequest)
            //result shouldBe ("TODO")
        }

    }
}
