/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package bisq.client.kotlin.operations

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bisq.client.kotlin.operations.InfoOperations
import bisq.client.kotlin.models.Info

class InfoOperationsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InfoOperations
        //val apiInstance = InfoOperations()

        // to test getInfo
        should("test getInfo") {
            // uncomment below to test getInfo
            //val result : Info = apiInstance.getInfo()
            //result shouldBe ("TODO")
        }

    }
}
