/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package bisq.client.kotlin.operations

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bisq.client.kotlin.operations.LoggingOperations
import bisq.client.kotlin.models.LoggingCategory
import bisq.client.kotlin.models.UpdateLoggingCategoryRequest

class LoggingOperationsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LoggingOperations
        //val apiInstance = LoggingOperations()

        // to test getLoggingCategories
        should("test getLoggingCategories") {
            // uncomment below to test getLoggingCategories
            //val result : kotlin.collections.List<LoggingCategory> = apiInstance.getLoggingCategories()
            //result shouldBe ("TODO")
        }

        // to test getLoggingCategory
        should("test getLoggingCategory") {
            // uncomment below to test getLoggingCategory
            //val name : kotlin.String = name_example // kotlin.String | 
            //val result : LoggingCategory = apiInstance.getLoggingCategory(name)
            //result shouldBe ("TODO")
        }

        // to test updateLoggingCategory
        should("test updateLoggingCategory") {
            // uncomment below to test updateLoggingCategory
            //val updateLoggingCategoryRequest : UpdateLoggingCategoryRequest =  // UpdateLoggingCategoryRequest | 
            //apiInstance.updateLoggingCategory(updateLoggingCategoryRequest)
        }

    }
}
