/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package bisq.client.kotlin.operations

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bisq.client.kotlin.operations.OfferbookOperations
import bisq.client.kotlin.models.AddOfferRequest
import bisq.client.kotlin.models.Offer

class OfferbookOperationsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OfferbookOperations
        //val apiInstance = OfferbookOperations()

        // to test addOffer
        should("test addOffer") {
            // uncomment below to test addOffer
            //val addOfferRequest : AddOfferRequest =  // AddOfferRequest | 
            //val result : kotlin.String = apiInstance.addOffer(addOfferRequest)
            //result shouldBe ("TODO")
        }

        // to test getOffer
        should("test getOffer") {
            // uncomment below to test getOffer
            //val offerId : kotlin.String = offerId_example // kotlin.String | 
            //val result : Offer = apiInstance.getOffer(offerId)
            //result shouldBe ("TODO")
        }

        // to test getOffers
        should("test getOffers") {
            // uncomment below to test getOffers
            //val result : kotlin.collections.List<Offer> = apiInstance.getOffers()
            //result shouldBe ("TODO")
        }

        // to test removeOffer
        should("test removeOffer") {
            // uncomment below to test removeOffer
            //val offerId : kotlin.String = offerId_example // kotlin.String | 
            //val result : Offer = apiInstance.removeOffer(offerId)
            //result shouldBe ("TODO")
        }

    }
}
