/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package bisq.client.kotlin.operations

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import bisq.client.kotlin.operations.UserOperations
import bisq.client.kotlin.models.CreateRequest

class UserOperationsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserOperations
        //val apiInstance = UserOperations()

        // to test create
        should("test create") {
            // uncomment below to test create
            //val createRequest : CreateRequest =  // CreateRequest | 
            //val result : kotlin.String = apiInstance.create(createRequest)
            //result shouldBe ("TODO")
        }

    }
}
